#!/bin/sh
# Fit the <n> curve with a sum of two arctan functions.
# Compute the derivative: chi1e-fit.dat
# RZ May 2022

mma --batchinput <<EOF

U = 0.333;
factor = 1/U;

l = Import["n1e.dat"];

fnc = 1/\[Pi] (ArcTan[(x - a)/b] + \[Pi]/2) +
  1/\[Pi] (ArcTan[(x - (2 - a))/b] + \[Pi]/2);
sol = FindFit[l, fnc, {{a, -0.28}, {b, 0.1}}, x]
fnc = fnc /. sol;

chi[x_] = factor D[fnc, x];
tab = Table[{x, chi[x]}, {x, -1, 3, 0.01}];

Export["chi1e-fit.dat", tab];
EOF

